#!/usr/bin/env sh

#exec /usr/lib/code-server/bin/code-server "$@"
#exec /pb/pocketbase serve "$@"
#exec touch /root/okoo & 

#nginx -g 'daemon off;' &

#/usr/lib/code-server/bin/code-server --bind-addr 0.0.0.0:8081

cat <<EOF > /etc/nginx/http.d/default.conf
server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
#for pocketbase
        location ~ /pb/(.*) {
                proxy_pass http://0.0.0.0:8090/\$1/;     
}
#for gitbucket
        location ~ /git/* {
                proxy_pass http://0.0.0.0:3000;     
                     #   proxy_pass http://localhost:3000;
             proxy_set_header        Host \$host;
        proxy_set_header        X-Real-IP \$remote_addr;
        proxy_set_header        X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_connect_timeout   150;
        proxy_send_timeout      100;
        proxy_read_timeout      100;
        proxy_buffers           4 32k;
        client_max_body_size    500m; # Big number is we can post big commits.
        client_body_buffer_size 128k;
}
#for vscode
        location / {
                proxy_pass http://0.0.0.0:8081;
     proxy_set_header Host \$host;
      proxy_set_header Upgrade \$http_upgrade;
      proxy_set_header Connection upgrade;
}
}
EOF

nginx -g 'daemon off;' &

#nginx -s reload; &

mkdir -p /root/pb &

mv /tmp/gitbucket.war -d /root/gitbucket.war &
nohup java -jar gitbucket.war --port=3000 --prefix=/git >/dev/null &
mv /tmp/gitbucket-ci-plugin-1.11.0.jar -d /root/.gitbucket/plugins/gitbucket-ci-plugin-1.11.0.jar &

unzip /tmp/pb.zip -d /root/pb &
nohup /root/pb/pocketbase serve >/dev/null &

/usr/lib/code-server/bin/code-server --bind-addr 0.0.0.0:8081
